[package]
name = "queue-poc-singleton"
version = "0.1.0"
authors = ["Rahul Anand <rahulanand16nov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
threescale = { path = "../threescale" }
proxy-wasm = "0.1.3"
log = "0.4"